java_test(
    name = "EndToEndInflateTest",
    size = "large",
    srcs = ["EndToEndInflateTest.java"],
    data = glob(["testdata/*.zz"]),
    deps = [
        "//src/main/java/com/google/io/pjflate",
        "//third_party:junit",
    ],
)
